%YAML:1.0

# /////////////////////////
# // IONLAB ISAE-SUPAERO //
# // TELLO SLAM PROJECT  //
# /////////////////////////

# Mode ////////////////////////////////////////////////////////////////////////
# test, mission
mode: test

verbose: 0

# Input ///////////////////////////////////////////////////////////////////////
# usb, video, tello
input_mode: video

# USB Camera
USB_camera_ID: 2

# Setting
setting_file_path: ./config/sensor_setting.yaml

# Video
video_file_path: /home/tershire/Videos/doors/matrix-backdoors.mp4

# Tello
tello_video_stream: "udp://0.0.0.0:11111"

# image size
input_resize_factor: 0.5
mono_camera_scale_factor: 1.0

# Output //////////////////////////////////////////////////////////////////////
resize_scale_factor: 1.25

# System //////////////////////////////////////////////////////////////////////
# which camera type is used for the mono camera: usb, raspberry
mono_camera_type: usb

# Aruco Detector //////////////////////////////////////////////////////////////
target_ID: 0
predifined_dictionary_name: DICT_5X5_50
marker_length: 14.5E-2

# data collection _____________________________________________________________
csv_file_name: run01.csv
