%YAML:1.0

# /////////////////////////
# // IONLAB ISAE-SUPAERO //
# // TELLO SLAM PROJECT  //
# /////////////////////////

# System //////////////////////////////////////////////////////////////////////
verbose: 1
draw_and_show: 1
save_video: 1
motion_log_on: 1 # 1 for true, 0 for false (if timestamps are not provided, set to false)

# Input ///////////////////////////////////////////////////////////////////////
# usb, video, tello
input_mode: usb

# Setting (camera to use)
mono_camera_to_use: usb
setting_file_path: ./config/sensor_setting.yaml

# USB Camera
USB_camera_ID: 0

# Video
video_file_path: /home/tershire/Videos/doors/20240224_res2_corridor-01.mp4

# Tello
tello_video_stream: "udp://0.0.0.0:11111"

# Output //////////////////////////////////////////////////////////////////////
resize_scale_factor: 0.5

# Aruco Detector //////////////////////////////////////////////////////////////
target_ID: 0
predifined_dictionary_name: DICT_4X4_50
marker_length: 4.9E-2

# data collection _____________________________________________________________
csv_file_name: output_data/run01
